experiment_name: "03a_atc_mean_gcn"

model:
  architecture: "gcn"
  hidden_dim: 128
  num_layers: 5
  dropout: 0.2
  heads: 3
  pooling: "mean"

training:
  epochs: 500
  batch_size: 32
  lr: 0.0001
  seed: 42

data:
  train_tasks: "atc"
  eval_tasks: "atc"
