experiment_name: "multitask_gcn_baseline"

model:
  architecture: "gcn"
  hidden_dim: 64
  num_layers: 5
  dropout: 0.2
  heads: 3

training:
  epochs: 50
  batch_size: 32
  lr: 0.001
  seed: 42

data:
  # max_side_effects: 200
  train_tasks: "side_effects,atc,maccs"
  eval_tasks: "side_effects"
